### ISSUE TITLE
alias-additions@v0.0.4: hash check failed

### ISSUE THREAD

**Issue by umbellipher** [snaphat/alias-additions#2]

**Comment by ebell451** [comment]
Updating 'alias-additions' (v0.0.3 -> v0.0.4)
Downloading new version
README.md (1.1 KB) [========================================] 100%
Checking hash of README.md ... ERROR Hash check failed!
App:         alias-additions/alias-additions
URL:         https://raw.githubusercontent.com/snaphat/alias-additions/master/README.md
First bytes: 23 20 61 6C 69 61 73 2D
Expected:    2ba805678c1a3633e5efd15edd94d50ee71785f70369449ebf55735836f66578
Actual:      1bb5878d806b2d273a84581668b38f436dcbbadfc4aadff2b0d3fe6dd1c81976

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/snaphat/alias-additions/issues/new?title=alias-additions%40v0.0.4%3a+hash+check+failed

**Comment by ebell451** [comment]
PR #3

**Comment by snaphat** [comment]
Merged and fixed via ebell451's PR, I forgot I had the Readme as the hash

**Comment by snaphat** [comment]
Just switched the hash to use an empty stub file since there is no external code outside of the json file (so this won't happen again).
